version: "3"

services:
  consent:
    image: consent_bb_demo_app
    expose:
      - 8000
    networks:
      - web
    build:
      context: .
      dockerfile: Dockerfile_app

  caddy:
    image: consent_bb_demo_http
    ports:
      - "8080:80"
      - "8888:443"
    environment:
      - SITE_ADDRESS=localhost
    volumes:
      - caddy:/data
    networks:
      - web
    build:
      context: .
      dockerfile: Dockerfile_caddy

volumes:
  caddy:

networks:
  web:
    driver: bridge
